--9 Create queries

--a)
select TEN
from SVIEN
where MAKHOA = 'CNTT'
go

--b)
select TENMH, TINCHI
from MHOC
go

--c)
select K.MASV, S.TEN, K.DIEM, H.MAHP, M.MAMH, M.TENMH
from KQUA K, HPHAN H, MHOC M, SVIEN S
where K.MASV = 8
AND K.MAHP = H.MAHP
AND H.MAMH = M.MAMH
AND K.MASV = S.MASV
go

--d)
select S.TEN, K.DIEM, H.MAMH
from KQUA K, HPHAN H, SVIEN S
where K.MAHP = H.MAHP
AND K.MASV = S.MASV
AND K.DIEM > 7
go

--e)
SELECT S.TEN
FROM SVIEN S, KHOA K, MHOC M
WHERE TENMH = 'Toán r?i r?c'
AND M.MAKHOA = K.MAKHOA
AND K.MAKHOA = S.MAKHOA

--f
SELECT MTRUOC.TENMH 'Môn tr??c', MSAU.TENMH 'Môn sau'
FROM MHOC MTRUOC, DKIEN D, MHOC MSAU
WHERE MTRUOC.MAMH = D.MAMH_TRUOC 
AND D.MAMH = MSAU.MAMH
AND MSAU.TENMH = 'C? s? d? li?u'

--g
SELECT MSAU.TENMH 'Môn sau', MTRUOC.TENMH 'Môn tr??c'
FROM MHOC MTRUOC, DKIEN D, MHOC MSAU
WHERE MTRUOC.MAMH = D.MAMH_TRUOC 
AND D.MAMH = MSAU.MAMH
AND MTRUOC.TENMH = 'C? s? d? li?u'

--h
-- CACH DU THUA (READ QUESTION CAREFULLY BEFORE SOLVE)
SELECT H.MAHP, COUNT(S.MASV) 'S? l??ng sinh viên ??ng ký'
FROM HPHAN H, SVIEN S, KQUA K
WHERE H.MAHP = K.MAHP
AND K.MASV = S.MASV
GROUP BY H.MAHP

-- CACH NGAN GON ?AY ?U
SELECT K.MAHP, COUNT(K.MASV) 'S? l??ng sinh viên ??ng ký'
FROM KQUA K
GROUP BY K.MAHP

--i

--j

--k
