USE MSTUDENT
--9 Create queries

--a)
select TEN
from SVIEN
where MAKHOA = 'CNTT'
go

--b)
select TENMH, TINCHI
from MHOC
go

--c)
select K.MASV, S.TEN, K.DIEM, H.MAHP, M.MAMH, M.TENMH
from KQUA K, HPHAN H, MHOC M, SVIEN S
where K.MASV = 8
and K.MAHP = 92
AND K.MAHP = H.MAHP
AND H.MAMH = M.MAMH
AND K.MASV = S.MASV
go

--d)
select S.TEN, K.DIEM, H.MAMH
from KQUA K, HPHAN H, SVIEN S
where K.MAHP = H.MAHP
AND K.MASV = S.MASV
AND K.DIEM > 7
go

--e)
SELECT S.TEN
FROM SVIEN S, KHOA K, MHOC M
WHERE TENMH = 'Toan r?i r?c'
AND M.MAKHOA = K.MAKHOA
AND K.MAKHOA = S.MAKHOA

--f
SELECT MTRUOC.TENMH 'Mon truoc', MSAU.TENMH 'Mon sau'
FROM MHOC MTRUOC, DKIEN D, MHOC MSAU
WHERE MTRUOC.MAMH = D.MAMH_TRUOC 
	AND D.MAMH = MSAU.MAMH
	AND MSAU.TENMH = 'C? s? d? li?u'

--g
SELECT MSAU.TENMH 'Mon sau', MTRUOC.TENMH 'Mon tr??c'
FROM MHOC MTRUOC, DKIEN D, MHOC MSAU
WHERE MTRUOC.MAMH = D.MAMH_TRUOC 
	AND D.MAMH = MSAU.MAMH
	AND MTRUOC.TENMH = 'C? s? d? li?u'

--h
-- CACH DU THUA (READ QUESTION CAREFULLY BEFORE SOLVE)
SELECT H.MAHP, COUNT(S.MASV) 'So luong sinh vien dang ky'
FROM HPHAN H, SVIEN S, KQUA K
WHERE H.MAHP = K.MAHP
	AND K.MASV = S.MASV
GROUP BY H.MAHP

-- CACH NGAN GON ?AY ?U
SELECT K.MAHP, COUNT(K.MASV) 'So luong sinh vien dang ky'
FROM KQUA K
GROUP BY K.MAHP

--i
SELECT S.MASV, S.TEN, --H.MAHP
	 H.NAM, SUM(K.DIEM * M.TINCHI) / SUM(M.TINCHI) 'Diem trung binh'
FROM SVIEN S, KQUA K, HPHAN H, MHOC M
WHERE S.MASV = K.MASV
	AND K.MAHP = H.MAHP
	AND H.MAMH = M.MAMH
GROUP BY S.MASV, S.TEN,
	-- H.HOCKY
	H.NAM

--j
SELECT S.TEN, K.DIEM
FROM SVIEN S, KQUA K
WHERE S.MASV = K.MASV
	AND K.DIEM = (SELECT MAX(DIEM) FROM KQUA)

--k
SELECT MASV, TEN
FROM SVIEN
WHERE MASV NOT IN (
	SELECT MASV
	FROM SVIEN S, KHOA K, MHOC M
	WHERE S.MAKHOA = K.MAKHOA
		AND K.MAKHOA = M.MAKHOA
		AND M.TENMH = 'Toan roi rac'
)